id: P009226
initial_creation_type: ocr
created_at: 23/03/2020
last_modified_at: 2021-12-19 19:28:55.022171
source_metadata:
  id: bdr:W8LS17835
  title: དག་ཡིག་ཉེར་མཁོ་གཅེས་བསྡུས།
  author: ''
  volumes:
    8546f26c12514699bf51c9d2b3a0c6e1:
      image_group_id: I8LS17852
      title: ''
      volume_number: 1
      total_pages: 33
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
