id: IBF7D9DD4
legacy_id: P009226
ocr_import_info:
  bdrc_scan_id: W8LS17835
  source: bdrc
  ocr_info:
    timestamp: '2020-03-23T06:34:28'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-04T03:59:29.030864+00:00'
last_modified: 2022-09-04 11:59:33.884622
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W8LS17835
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW8LS17835
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: དག་ཡིག་ཉེར་མཁོ་གཅེས་བསྡུས།
statistics:
  ocr_word_mean_confidence_index: 0.5023317884926557
  ocr_word_median_confidence_index: 0.4699999988079071
quality: null
bases:
  I8LS17852:
    source_metadata:
      id: http://purl.bdrc.io/resource/I8LS17852
      total_pages: 33
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I8LS17852.txt
    statistics:
      ocr_word_median_confidence_index: 0.4699999988079071
      ocr_word_mean_confidence_index: 0.5023317884926557
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
